# Generated by Django 2.1.5 on 2021-01-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210118_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='oo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(default='444'),
        ),
    ]
